# Generated by Django 3.1.5 on 2021-01-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='measure',
            field=models.CharField(choices=[('грамм', 'г'), ('стакан', 'ст')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Уникальный URL'),
        ),
    ]
