# Generated by Django 3.1.5 on 2021-01-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210131_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='default', max_length=20, verbose_name='Цвет тега'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='display_name',
            field=models.CharField(default='default', max_length=20, verbose_name='Имя тега в шаблоне'),
            preserve_default=False,
        ),
    ]
