# Generated by Django 3.1.5 on 2021-01-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210124_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='count',
        ),
    ]
