# Generated by Django 3.1.5 on 2021-01-31 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210131_2214'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='follow',
            name='author',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
