# Generated by Django 3.1.5 on 2021-01-26 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_remove_ingredient_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients_amount',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measure',
            field=models.CharField(choices=[('грамм', 'г.'), ('стакан', 'стакан'), ('кусок', 'кусок'), ('штук', 'шт.'), ('по вкусу', 'по вкусу'), ('столовые ложки', 'ст.л.'), ('чайные ложки', 'ч.л.'), ('миллилитр', 'мл.')], default=None, max_length=20),
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'recipe')},
            },
        ),
    ]
