# Generated by Django 3.1.5 on 2021-01-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipe_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='measure',
        ),
        migrations.RemoveField(
            model_name='number',
            name='recipe',
        ),
        migrations.AddField(
            model_name='number',
            name='measure',
            field=models.CharField(choices=[('грамм', 'г.'), ('стакан', 'стакан'), ('кусок', 'кусок'), ('штук', 'шт.'), ('по вкусу', 'по вкусу'), ('столовые ложки', 'ст.л.'), ('чайные ложки', 'ч.л.'), ('миллилитр', 'мл.')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='recipes.Number', verbose_name='Инградиенты'),
        ),
    ]
