# Generated by Django 3.1.5 on 2021-01-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210126_2156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Number',
            new_name='RecipeIngredient',
        ),
    ]
