# Generated by Django 3.1.5 on 2021-01-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20210126_2246'),
        ('recipes', '0007_auto_20210126_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Инградиент (рецепт)', 'verbose_name_plural': 'Инградиенты (рецепт)'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='tags.Tag', verbose_name='Теги'),
        ),
    ]
