# Generated by Django 3.1.5 on 2021-01-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20210126_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранный рецепт', 'verbose_name_plural': 'Избранные рецепты'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='measure',
            field=models.CharField(choices=[('грамм', 'г.'), ('стакан', 'стакан'), ('кусок', 'кусок'), ('штук', 'шт.'), ('по вкусу', 'по вкусу'), ('столовые ложки', 'ст.л.'), ('чайные ложки', 'ч.л.'), ('мл.', 'мл.')], default=None, max_length=20),
        ),
    ]
