# Generated by Django 3.1.5 on 2021-01-27 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0011_auto_20210127_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recipe', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recipe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='measure',
            field=models.CharField(choices=[('г.', 'г.'), ('стакан', 'стакан'), ('кусок', 'кусок'), ('шт.', 'шт.'), ('по вкусу', 'по вкусу'), ('ст.л.', 'ст.л.'), ('ч.л.', 'ч.л.'), ('мл.', 'мл.')], default=None, max_length=20),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рецепты (покупка)',
                'verbose_name_plural': 'Рецепты (покупка)',
                'unique_together': {('user', 'recipe')},
            },
        ),
    ]
